services:
  wordpress_javier_1:  
    image: wordpress
    ports: 
    - "8080:80" 
  wordpress_javier_2:  
    image: wordpress
    ports: 
    - "8081:80" 
  wordpress_javier_3:  
    image: wordpress
    ports: 
    - "8082:80" 
  wordpress_javier_4:  
   image: wordpress
   ports: 
   - "8083:80" 