# Nombre del proyecto en SonarQube
sonar.projectKey=task-manager-java

# Nombre visible en el tablero de SonarQube
sonar.projectName=Task Manager Java

# Versión del proyecto
sonar.projectVersion=1.0

# Indicar que el proyecto es en Java
sonar.language=java

# Directorio donde está el código fuente
sonar.sources=.

# Codificación del código fuente
sonar.sourceEncoding=UTF-8

# Tipo de cobertura de código (si usas cobertura con JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
