version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/init.js:/docker-entrypoint-initdb.d/init.js

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
