-- JAVIER LÓPEZ GUTIÉRREZ
CREATE DATABASE IF NOT EXISTS PRACTICA_HISTORIAL_SALARIAL;
USE PRACTICA_HISTORIAL_SALARIAL;

DROP TABLE IF EXISTS HISTORIAL_LABORAL;
DROP TABLE IF EXISTS HISTORIAL_SALARIAL;
DROP TABLE IF EXISTS TRABAJOS;
DROP TABLE IF EXISTS ESTUDIOS;
DROP TABLE IF EXISTS UNIVERSIDADES;
DROP TABLE IF EXISTS DEPARTAMENTOS;
DROP TABLE IF EXISTS EMPLEADOS;


CREATE TABLE EMPLEADOS(
    DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDO1 VARCHAR(15) NOT NULL,
    APELLIDO2 VARCHAR(15),
    DIRECC1 VARCHAR(25),
    DIRECC2 VARCHAR(25),
    CIUDAD VARCHAR(20),
    MUNICIPIO VARCHAR(20),
    COD_POSTAL VARCHAR(5),
    SEXO CHAR(1) CHECK (SEXO IN ('H','M','O')),
    FECHA_NAC DATE
);

CREATE TABLE DEPARTAMENTOS (
    DPTO_COD DECIMAL(5) PRIMARY KEY,
    NOMBRE_DPTO VARCHAR(30) NOT NULL UNIQUE,
    JEFE CHAR(9),
    PRESUPUESTO INTEGER NOT NULL,
    PRES_ACTUAL INTEGER,
    
    CONSTRAINT FK_JEFE FOREIGN KEY (JEFE) REFERENCES EMPLEADOS(DNI) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE TRABAJOS(
    CODIGO DECIMAL(5) PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL UNIQUE,
    SALARIO_MIN DECIMAL(10,2) NOT NULL, 
    SALARIO_MAX DECIMAL(10,2) NOT NULL
);


CREATE TABLE HISTORIAL_LABORAL(
    EMPLEADO_DNI CHAR(9),
    TRAB_COD DECIMAL(5),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DPTO_COD DECIMAL(5),
    SUPERVISOR_DNI CHAR(9),
    
    PRIMARY KEY (EMPLEADO_DNI, FECHA_INICIO), -- 5 Un solo trabajo en cada momento
    CONSTRAINT FK_HIST_LAB_EMP FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT FK_HIST_LAB_TRAB FOREIGN KEY (TRAB_COD) REFERENCES TRABAJOS(CODIGO) ON UPDATE CASCADE,
    CONSTRAINT FK_HIST_LAB_DPTO FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS(DPTO_COD) ON UPDATE CASCADE,
    CONSTRAINT CHK_FECHAS_LAB CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO)
);

CREATE TABLE HISTORIAL_SALARIAL(
    EMPLEADO_DNI CHAR(9),
    SALARIO INTEGER NOT NULL,
    FECHA_COMIENZO DATE NOT NULL,
    FECHA_FIN DATE,
    PRIMARY KEY (EMPLEADO_DNI, FECHA_COMIENZO), -- 5 Un solo salario en cada momento
    CONSTRAINT FK_HIST_SAL_EMP FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT CHK_FECHAS_SAL CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_COMIENZO)
);

-- 8. Índice de TRABAJOS 
CREATE INDEX IDX_TRABAJOS_NOMBRE ON TRABAJOS(NOMBRE);

-- 9. Índice de EMPLEADOS 
CREATE INDEX IDX_EMPLEADOS_ORDENADOS ON EMPLEADOS(APELLIDO1, APELLIDO2, NOMBRE);

-- 10. Modificar HISTORIAL_LABORAL
ALTER TABLE HISTORIAL_LABORAL 
ADD CONSTRAINT FK_LABORAL_SALARIAL 
FOREIGN KEY (EMPLEADO_DNI, FECHA_INICIO) 
REFERENCES HISTORIAL_SALARIAL(EMPLEADO_DNI, FECHA_COMIENZO)
ON UPDATE CASCADE ON DELETE CASCADE;