-- Ejemplos de CREATE TABLE
-------------------------------
-- 
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;

CREATE TABLE PAIS(
	COD		NUMBER(5) PRIMARY KEY,		
	NOMBRE	VARCHAR2(15) 
);

-- A) Con restricciones de tabla
CREATE TABLE PRODUCTOS(
	COD		NUMBER(5),		
	NOMBRE	VARCHAR2(15), 
	PAIS	NUMBER(5),
	PRIMARY KEY(COD),
	CHECK(NOMBRE=UPPER(NOMBRE)), 
	FOREIGN KEY (PAIS) REFERENCES PAIS 
);
-- B) Con restricciones de columna
CREATE TABLE PRODUCTOS(
	COD		NUMBER(5)		PRIMARY KEY,		
	NOMBRE	VARCHAR2(15)	CHECK(NOMBRE=UPPER(NOMBRE)), 
	PAIS	NUMBER(5) 		REFERENCES PAIS 
);
-- C) Con restricciones de tabla y nombre de cada restricción
CREATE TABLE PRODUCTOS(
	COD		NUMBER(5),		
	NOMBRE	VARCHAR2(15), 
	PAIS	NUMBER(5),
	CONSTRAINT PK_PROD PRIMARY KEY(COD),
	CONSTRAINT CK_NOMB CHECK(NOMBRE=UPPER(NOMBRE)), 
	CONSTRAINT FK_PAIS FOREIGN KEY (PAIS) REFERENCES PAIS 
);
-- D) Con restricciones de columna y nombre de cada restricción
CREATE TABLE PRODUCTOS(
	COD		NUMBER(5)		CONSTRAINT PK_PROD PRIMARY KEY,		
	NOMBRE	VARCHAR2(15)	CONSTRAINT CK_NOMB CHECK(NOMBRE=UPPER(NOMBRE)), 
	PAIS	NUMBER(5) 		CONSTRAINT FK_PAIS REFERENCES PAIS 
);
-- E) Creación de Tabla sin restricciones, añadiendo las restricciones con ALTER TABLE
CREATE TABLE PRODUCTOS(
	COD		NUMBER(5),		
	NOMBRE	VARCHAR2(15), 
	PAIS	NUMBER(5)
);

ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PROD PRIMARY KEY(COD);
ALTER TABLE PRODUCTOS ADD CONSTRAINT CK_NOMB CHECK(NOMBRE=UPPER(NOMBRE));
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PAIS FOREIGN KEY (PAIS) REFERENCES PAIS;

